### Resources
* https://learningtensorflow.com

In [6]:
import tensorflow as tf
import numpy as np

In [7]:
x = tf.constant(np.array([35,40,45]), name='x')
y = tf.Variable(x + 5, name='y')

with tf.Session() as session:
    session.run(tf.global_variables_initializer())
    print(session.run(y))

[40 45 50]


In [10]:
a = tf.constant([[1,2,3],[4,5,6]],name="a")
b = tf.constant([[100,101,102]], name="b")
add_op = a + b

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(add_op))

[[101 103 105]
 [104 106 108]]


In [ ]:
def create_samples(n_clusters, n_samples_per_cluster, n_features, embiggen_factor, seed):
    np.random.seed(seed)
    slices = []
    centroids = []
    
    for i in range(n_clusters):
        samples = tf.random_normal((n_samples_per_cluster, n_features),\
                                  mean=0.0, stddev=5.0, dtype=tf.float32, seed=seed, name="cluster_{}".format(i))
        current_centroid = (np.random.random((1, n_features))*embiggen_factor)-(embiggen_factor/2)
        centroids.append(current_centroid)
        samples += current_centroid
        slices.append(samples)
    
    samples = tf.concat(slices, 0, name="samples")
    centroids = tf.concat(centroids, 0, name="centroids")
    return centroids, samples